### ISSUE TITLE
Error with sound, cutscenes and pause menu

### ISSUE THREAD

**Issue by thedingsedreng** [hmxmilohax/rock-band-2-deluxe#6]
As of the newest version (16th of October, 3.15 PM UTC) I've experienced an ongoing issue, with sound effects not being present when playing a song. Complete silence before and after the song, and during the song, only the stems can be heard - causing an effect of sitting in studio/sound stage.
The cutscenes before songs is bugged so it shows double, exposing and hiding the highway in between the cutscenes.
when playing a song, the pause button doesn't work.

All of this is tested on drums in Tour mode on RPCS3.

**Comment by SCOTT0852** [comment]
I don't know about the sfx bug, but the double start cutscene is intentional (it prevents a bug where the first notes would be invisible until you restart the song, so the double start is it restarting for you as soon as it can). 
I've been having the pause bug as well on the latest commits (on guitar, I haven't tested drums and can't at the moment).

**Comment by BlinkzFox** [comment]
I'm getting the sound bug too. The crowd audio just fades out at the beginning and doesn't come back.

**Comment by jnackmclain** [comment]
[f66b1d5](https://github.com/hmxmilohax/rock-band-2-deluxe/commit/f66b1d50955c6ee1d7c2513434222b033c46359b) should fix this issue. sorry it was negected
